spring:
  application:
    name: Springboot_FashionWeb
  security:
    user: # tạo user mặc định phục vụ phart triển
      name: user
      password: # Để trống để Spring Boot tự tạo mật khẩu ngẫu nhiên

  datasource:
    url: jdbc:mysql://fashionista.clcm6y6k0f9i.ap-southeast-2.rds.amazonaws.com:3306/fashionista?useSSL=false&serverTimezone=UTC
    username: admin
    password: 987654321

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: laptrinhh2208@gmail.com
    password: bewq lkvf saii sasu
    properties.mail:
      smtp:
        auth: true
        starttls.enable: true

server:
  port: 8091

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

storage:
  location: C:\\Upload
