spring:
  application:
    name: Springboot_FashionWeb
  security:
    user: # tạo user mặc định phục vụ phart triển
      name: user
      password: # Để trống để Spring Boot tự tạo mật khẩu ngẫu nhiên

  datasource:

#    jdbc:mysql://localhost:3306/fashionista
      url: jdbc:mysql://fashionista.clcm6y6k0f9i.ap-southeast-2.rds.amazonaws.com:3306/fashionista?useSSL=false&serverTimezone=UTC
      username: admin
      password: 987654321

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: laptrinhh2208@gmail.com
    password: bewq lkvf saii sasu
    properties.mail:
      smtp:
        auth: true
        starttls.enable: true

server:
  port: 8091

jwt:
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  expiration: 3600  # 1 hour

storage:
  location: D:\\Upload
